import type { Property } from "./types";

/**
 * Catálogo de propiedades.
 *
 * ⚠️ ESTOS DATOS SON DE EJEMPLO. No corresponden a propiedades reales: sirven
 * para poder ver y probar la pantalla de resultados hasta que se carguen las
 * de REMAX y del equipo. Antes de mostrarle esto a alguien de afuera, hay que
 * reemplazarlas.
 *
 * CÓMO ADMINISTRARLAS (mientras el catálogo viva en este archivo):
 *
 *   Agregar      → copiar un bloque, cambiarle el `id` y la `reference`.
 *   Editar       → cambiar el campo y actualizar `updated_at`.
 *   Cambiar precio → `price` + `updated_at`.
 *   Vendida / alquilada / no disponible → `active: false`. Deja de aparecer en
 *                  resultados y su ficha devuelve 404. No hace falta borrarla,
 *                  y así queda el historial.
 *   Confirmar que sigue disponible → actualizar `last_verified_at`. Si pasan
 *                  más de 30 días, la ficha avisa que hay que reconfirmar.
 *   Fotos        → poner archivos en `public/propiedades/` y referenciarlos
 *                  como "/propiedades/archivo.jpg". Con `images: []` se muestra
 *                  un placeholder.
 *   URL externa  → `external_url` con el enlace a la publicación original.
 *
 * Las fechas van en ISO (YYYY-MM-DD).
 */
export const PROPIEDADES: Property[] = [
  {
    id: "prop_001",
    reference: "REMAX-12345",
    operation: "venta",
    property_type: "apartamento",
    title: "Apartamento de 2 dormitorios en Pocitos",
    department: "Montevideo",
    neighborhood: "Pocitos",
    price: 275000,
    currency: "USD",
    bedrooms: 2,
    bathrooms: 2,
    area: 78,
    common_expenses: 7800,
    features: ["garaje", "balcon"],
    images: ["/propiedades/prop_001.webp"],
    external_url: "",
    active: true,
    created_at: "2026-07-02",
    updated_at: "2026-08-10",
    last_verified_at: "2026-08-10",
  },
  {
    id: "prop_002",
    reference: "REMAX-12360",
    operation: "venta",
    property_type: "apartamento",
    title: "Apartamento a estrenar en Punta Carretas",
    department: "Montevideo",
    neighborhood: "Punta Carretas",
    price: 345000,
    currency: "USD",
    bedrooms: 2,
    bathrooms: 2,
    area: 92,
    common_expenses: 11500,
    features: ["garaje", "balcon", "piscina"],
    images: ["/propiedades/prop_002.webp"],
    external_url: "",
    active: true,
    created_at: "2026-07-14",
    updated_at: "2026-08-12",
    last_verified_at: "2026-08-12",
  },
  {
    id: "prop_003",
    reference: "REMAX-12377",
    operation: "venta",
    property_type: "apartamento",
    title: "Apartamento con vista al mar en Buceo",
    department: "Montevideo",
    neighborhood: "Buceo",
    price: 198000,
    currency: "USD",
    bedrooms: 1,
    bathrooms: 1,
    area: 55,
    common_expenses: 5400,
    features: ["balcon", "garaje"],
    images: ["/propiedades/prop_003.webp"],
    external_url: "",
    active: true,
    created_at: "2026-06-20",
    updated_at: "2026-08-05",
    last_verified_at: "2026-08-05",
  },
  {
    id: "prop_004",
    reference: "REMAX-12401",
    operation: "venta",
    property_type: "casa",
    title: "Casa con jardín y parrillero en Carrasco",
    department: "Montevideo",
    neighborhood: "Carrasco",
    price: 480000,
    currency: "USD",
    bedrooms: 4,
    bathrooms: 3,
    area: 240,
    common_expenses: null,
    features: ["jardin", "parrillero", "garaje", "piscina"],
    images: [],
    external_url: "",
    active: true,
    created_at: "2026-05-30",
    updated_at: "2026-08-01",
    last_verified_at: "2026-08-01",
  },
  {
    id: "prop_005",
    reference: "REMAX-12415",
    operation: "venta",
    property_type: "casa",
    title: "Casa de 3 dormitorios en Punta Gorda",
    department: "Montevideo",
    neighborhood: "Punta Gorda",
    price: 365000,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 2,
    area: 175,
    common_expenses: null,
    features: ["jardin", "parrillero", "garaje"],
    images: [],
    external_url: "",
    active: true,
    created_at: "2026-06-11",
    updated_at: "2026-07-28",
    last_verified_at: "2026-07-28",
  },
  {
    id: "prop_006",
    reference: "REMAX-12428",
    operation: "venta",
    property_type: "apartamento",
    title: "Monoambiente reciclado en Ciudad Vieja",
    department: "Montevideo",
    neighborhood: "Ciudad Vieja",
    price: 89000,
    currency: "USD",
    bedrooms: 0,
    bathrooms: 1,
    area: 38,
    common_expenses: 3900,
    features: ["amoblado"],
    images: [],
    external_url: "",
    active: true,
    created_at: "2026-07-22",
    updated_at: "2026-08-14",
    last_verified_at: "2026-08-14",
  },
  {
    id: "prop_007",
    reference: "REMAX-12440",
    operation: "venta",
    property_type: "apartamento",
    title: "Apartamento de 3 dormitorios en Parque Batlle",
    department: "Montevideo",
    neighborhood: "Parque Batlle",
    price: 232000,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 2,
    area: 105,
    common_expenses: 9200,
    features: ["garaje", "terraza"],
    images: ["/propiedades/prop_007.webp"],
    external_url: "",
    active: true,
    created_at: "2026-06-02",
    updated_at: "2026-08-08",
    last_verified_at: "2026-08-08",
  },
  {
    id: "prop_008",
    reference: "REMAX-12455",
    operation: "alquiler",
    property_type: "apartamento",
    title: "Apartamento amoblado de 1 dormitorio en Cordón",
    department: "Montevideo",
    neighborhood: "Cordón",
    price: 26500,
    currency: "UYU",
    bedrooms: 1,
    bathrooms: 1,
    area: 48,
    common_expenses: 4800,
    features: ["amoblado", "balcon"],
    images: [],
    external_url: "",
    active: true,
    created_at: "2026-07-30",
    updated_at: "2026-08-15",
    last_verified_at: "2026-08-15",
  },
  {
    id: "prop_009",
    reference: "REMAX-12462",
    operation: "alquiler",
    property_type: "apartamento",
    title: "Apartamento de 2 dormitorios en Malvín",
    department: "Montevideo",
    neighborhood: "Malvín",
    price: 38000,
    currency: "UYU",
    bedrooms: 2,
    bathrooms: 1,
    area: 66,
    common_expenses: 6100,
    features: ["balcon", "garaje", "mascotas"],
    images: [],
    external_url: "",
    active: true,
    created_at: "2026-08-01",
    updated_at: "2026-08-15",
    last_verified_at: "2026-08-15",
  },
  {
    id: "prop_010",
    reference: "REMAX-12470",
    operation: "alquiler",
    property_type: "casa",
    title: "Casa de 3 dormitorios en Solymar",
    department: "Canelones",
    neighborhood: "Solymar",
    price: 45000,
    currency: "UYU",
    bedrooms: 3,
    bathrooms: 2,
    area: 140,
    common_expenses: null,
    features: ["jardin", "parrillero", "garaje", "mascotas"],
    images: [],
    external_url: "",
    active: true,
    created_at: "2026-07-18",
    updated_at: "2026-08-13",
    last_verified_at: "2026-08-13",
  },
  {
    id: "prop_011",
    reference: "REMAX-12488",
    operation: "venta",
    property_type: "casa",
    title: "Casa a metros de la playa en Ciudad de la Costa",
    department: "Canelones",
    neighborhood: "Ciudad de la Costa",
    price: 168000,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 2,
    area: 130,
    common_expenses: null,
    features: ["jardin", "parrillero", "garaje"],
    images: [],
    external_url: "",
    active: true,
    created_at: "2026-06-25",
    updated_at: "2026-08-06",
    last_verified_at: "2026-08-06",
  },
  {
    id: "prop_012",
    reference: "REMAX-12495",
    operation: "venta",
    property_type: "terreno",
    title: "Terreno de 600 m² en El Pinar",
    department: "Canelones",
    neighborhood: "El Pinar",
    price: 62000,
    currency: "USD",
    bedrooms: 0,
    bathrooms: 0,
    area: 600,
    common_expenses: null,
    features: [],
    images: [],
    external_url: "",
    active: true,
    created_at: "2026-05-12",
    updated_at: "2026-07-20",
    last_verified_at: "2026-07-20",
  },
  {
    id: "prop_013",
    reference: "REMAX-12502",
    operation: "venta",
    property_type: "apartamento",
    title: "Apartamento frente al mar en Punta del Este",
    department: "Maldonado",
    neighborhood: "Punta del Este",
    price: 395000,
    currency: "USD",
    bedrooms: 2,
    bathrooms: 2,
    area: 98,
    common_expenses: 14500,
    features: ["balcon", "piscina", "garaje", "amoblado"],
    images: [],
    external_url: "",
    active: true,
    created_at: "2026-06-08",
    updated_at: "2026-08-11",
    last_verified_at: "2026-08-11",
  },
  {
    id: "prop_014",
    reference: "REMAX-12518",
    operation: "venta",
    property_type: "local",
    title: "Local comercial sobre avenida en Tres Cruces",
    department: "Montevideo",
    neighborhood: "Tres Cruces",
    price: 145000,
    currency: "USD",
    bedrooms: 0,
    bathrooms: 1,
    area: 85,
    common_expenses: 6800,
    features: [],
    images: [],
    external_url: "",
    active: true,
    created_at: "2026-07-05",
    updated_at: "2026-08-09",
    last_verified_at: "2026-08-09",
  },
  {
    id: "prop_015",
    reference: "REMAX-12099",
    operation: "venta",
    property_type: "apartamento",
    title: "Apartamento de 2 dormitorios en Pocitos (vendido)",
    department: "Montevideo",
    neighborhood: "Pocitos",
    price: 249000,
    currency: "USD",
    bedrooms: 2,
    bathrooms: 1,
    area: 70,
    common_expenses: 7200,
    features: ["balcon"],
    images: [],
    external_url: "",
    // Queda como ejemplo de propiedad dada de baja: no debe aparecer nunca.
    active: false,
    created_at: "2026-03-14",
    updated_at: "2026-07-01",
    last_verified_at: "2026-07-01",
  },
];

/** Sólo las que se pueden mostrar. Es el único acceso al catálogo. */
export function propiedadesActivas(): Property[] {
  return PROPIEDADES.filter((propiedad) => propiedad.active);
}

/** Busca por id, respetando el estado activo. */
export function buscarPropiedad(id: string) {
  return propiedadesActivas().find((propiedad) => propiedad.id === id);
}
